### ISSUE TITLE
Relative path in Script

### ISSUE THREAD

**Issue by mejmo** [aefimov/idea-batch#22]
Is there any variable so that I could have relative path in Script textbox? I would like to share this Run configuration in VCS but I cannot because it uses absolute path.

**Comment by tlf30** [comment]
I second this. I just had this same issue where we have scripts setup that need to be the same for all developers and would be awesome if this could use relative paths.

**Comment by SimonIT** [comment]
PR's are welcome

**Comment by tlf30** [comment]
I'll have one ready in a couple hours.

**Comment by tlf30** [comment]
Please see #38.
I have done some testing, but it probably needs some extensive testing to ensure that it does not break anything.

**Comment by tlf30** [comment]
@SimonIT 
Any ideas as to when this will be released in an update?

**Comment by SimonIT** [comment]
I can make one now

**Comment by tlf30** [comment]
That sounds good to me
