### ISSUE TITLE
Plugin can't be installed on other IDEA based products

### ISSUE THREAD

**Issue by axelcostaspena** [aefimov/idea-batch#23]
My team need to install it on PhpStorm in order to use BATCH run configurations. Can you please review the plugin definition file? There you can configure the plugin compatibilities. It's very possible that your plugin will run perfectly inside PhpStorm, it's just a matter of changing the compatibilities definition. Hope I am not taking wrong assumptions. Thank you in advance!

**Comment by axelcostaspena** [comment]
BTW, if you download the jar manually and install it it doesn't show any error, but the "Batch" run configuration type doesn't show on the "Create run configuration" dialog.

**Comment by aefimov** [comment]
Hello, this plugin is unsupported for many years. As i know Intellij Platform already have batch syntax support on board.

**Comment by axelcostaspena** [comment]
Yes, but they don't provide run ocnfigurations as your plugin does. Your plugin is still a must have.
