### ISSUE TITLE
IllegalStateException regularly occurrs

### ISSUE THREAD

**Issue by fdfdkeodoccca** [aefimov/idea-batch#28]
Several times a day I get Intellij reporting an exception occurred in this plugin. the (shortened)  stacktrace is below:

java.lang.IllegalStateException: TextAttributeKey(name:'BATCH.BRACES', fallbackAttributeKey:'DEFAULT_BRACKETS')  was already registered with the other fallback attribute key: DEFAULT_BRACES
	at com.intellij.openapi.editor.colors.TextAttributesKey.mergeKeys(TextAttributesKey.java:215)
	at com.intellij.openapi.editor.colors.TextAttributesKey.lambda$getOrCreate$4(TextAttributesKey.java:201)

It seems to happen even when I am not editing any batch files, I am working on other files.

![intellij_error](https://user-images.githubusercontent.com/49756092/56364082-a5e27e80-61e5-11e9-8b9c-dc3b0b4640d7.PNG)

The "Report Exception" button is disabled (this could be Intellij bug and not related to the plugin) so I decided to report the bug here.

**Comment by SimonIT** [comment]
Duplicate to #26, this is fixed in my fork SimonIT/idea-batch

**Comment by fdfdkeodoccca** [comment]
I suggest this issue is closed to avoid confusion then,
