### ISSUE TITLE
Red underlines after `if defined`

### ISSUE THREAD

**Issue by rgoldberg** [aefimov/idea-batch#39]
Running on IntelliJ IDEA 2020.1 EAP on macOS 10.15.2, there are red underlines after `if defined` on line 36 of `gradlew.bat` version 6.1 (see attached [gradlew.txt](https://github.com/aefimov/idea-batch/files/4110945/gradlew.txt), as GitHub won't accept `.bat` attachments).

No error is reported, however.

I don't know if this issue occurs on other versions of IntelliJ, on other platforms, for all uses of `if defined`, etc.

**Comment by SimonIT** [comment]
Duplicate to #21. I'm not very familiar with the lexer code. I'll have to have a closer look on it. If yo could provide a PR I would be very happy
