### ISSUE TITLE
Move command dont works

### ISSUE THREAD

**Issue by Radon8472** [aefimov/idea-batch#44]
When I try to run the move command it always shows:

```
cmd.exe /c move config\server\dump.sql.gz config\
Das System kann die angegebene Datei nicht finden.
```
I tried to add the command as Script, I tried to add `move` as Script and the remaining arguments as "Parameter"
But nothing works.

I tried to run `pwd` to ensure the script is executed un the correct directory and this was okay.
When I run the same command from a cmd-shell in the same working directory everythings works fine.

**Comment by Radon8472** [comment]
After some more tests it finally worked

**Comment by SimonIT** [comment]
Nice to hear
