### ISSUE TITLE
The dark blue text color used by this plugin is unreadable on IntelliJ's new 'Darcula' theme

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aefimov/idea-batch#7]
```
What steps will reproduce the problem?
1. Install the Batch Language plugin
2. Open the editor to show a batch file
3. Observe horrible lack of text contrast

```

Original issue reported on code.google.com by `christop...@gmail.com` on 24 Jan 2014 at 12:32

**Comment by cezary-butler** [comment]
Please see if this build works for you https://github.com/Programisci/idea-batch/releases/tag/v1.0.6-Programisci.eu.
If it does I'll make a pull request

**Comment by aefimov** [comment]
Hello, can you please make PR? Thanks
